title: "GIS Workshops"
remote_theme: pmarsceill/just-the-docs
description: GIS workshops hosted by UMass Amherst Libraries

# Magic to make URLs resolve both locally and on GitHub.
# See https://help.github.com/articles/repository-metadata-on-github-pages/.
repository: umass-gis/workshops

# Set a path/url to a logo that will be displayed instead of the title
logo: "assets/images/umass.png"

# Aux links for the upper right navigation
aux_links:
  "View these workshops on GitHub":
    - "//github.com/umass-gis/workshops"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: true

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: "Copyright &copy; 2023. Distributed by an <a href=\"https://github.com/umass-gis/workshops/blob/main/LICENSE.txt\">Creative Commons Attribution 4.0 International license.</a>"

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Color scheme currently only supports "dark", "light"/nil (default), or a custom scheme that you define
color_scheme: umass

# Google Analytics Tracking (optional)
# e.g, UA-1234567-89
# ga_tracking: G-MVHTPQ8CLM
