title: "GIS Workshops"
remote_theme: pmarsceill/just-the-docs
description: GIS workshops hosted by UMass Amherst Libraries

# Footer content
# appears at the bottom of every page's main content

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

footer_content: <a href="https://github.com/umass-gis/workshops" target="_blank">View this workshop in GitHub</a>

# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

plugins:
  - jekyll-feed
  - jekyll-seo-tag
